-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 10:18:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_marESol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_marESol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_marESol` DEFAULT CHARACTER SET utf8 ;
USE `db_marESol` ;

-- -----------------------------------------------------
-- Table `db_marESol`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nomeCategoria` VARCHAR(50) NOT NULL,
  `status` CHAR(1) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(100) NOT NULL,
  `peso` FLOAT(4,2) NOT NULL,
  `preco` FLOAT(5,2) NOT NULL,
  `imagem` VARCHAR(200) NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `status` CHAR(1) NULL DEFAULT 'A',
  PRIMARY KEY (`idProduto`, `Categoria_idCategoria`),
  CONSTRAINT `fk_Produto_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `db_marESol`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NOT NULL,
  `estado` VARCHAR(60) NOT NULL,
  `cidade` VARCHAR(60) NOT NULL,
  `bairro` VARCHAR(60) NOT NULL,
  `rua` VARCHAR(60) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(256) NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(15) NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Endereco_idEndereco`),
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `db_marESol`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Entregador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Entregador` (
  `idEntregador` INT NOT NULL AUTO_INCREMENT,
  `nomeEntregador` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(15) NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idEntregador`, `Endereco_idEndereco`),
  CONSTRAINT `fk_Entregador_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `db_marESol`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `total_vendas` FLOAT(7,2) NOT NULL,
  `observacao` VARCHAR(256) NULL,
  `Entregador_idEntregador` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVenda`, `Entregador_idEntregador`, `Cliente_idCliente`),
  CONSTRAINT `fk_Venda_Entregador1`
    FOREIGN KEY (`Entregador_idEntregador`)
    REFERENCES `db_marESol`.`Entregador` (`idEntregador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `db_marESol`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Item` (
  `Venda_idVenda` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Produto_Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`Venda_idVenda`, `Produto_idProduto`, `Produto_Categoria_idCategoria`),
  CONSTRAINT `fk_Venda_has_Produto_Venda1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `db_marESol`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Produto1`
    FOREIGN KEY (`Produto_idProduto` , `Produto_Categoria_idCategoria`)
    REFERENCES `db_marESol`.`Produto` (`idProduto` , `Categoria_idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nomeCategoria` VARCHAR(50) NOT NULL,
  `status` CHAR(1) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(100) NOT NULL,
  `peso` FLOAT(4,2) NOT NULL,
  `preco` FLOAT(5,2) NOT NULL,
  `imagem` VARCHAR(200) NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `status` CHAR(1) NULL DEFAULT 'A',
  PRIMARY KEY (`idProduto`, `Categoria_idCategoria`),
  CONSTRAINT `fk_Produto_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `db_marESol`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nomeEstado` CHAR(2) NOT NULL,
  PRIMARY KEY (`idEstado`),
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(50) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  `status` CHAR(1) NULL DEFAULT 'A',
  PRIMARY KEY (`idCidade`, `Estado_idEstado`),
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `db_marESol`.`Estado` (`idEstado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nomeEmpresa` VARCHAR(100) NOT NULL,
  `CNPJ` CHAR(18) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `nomeCliente` VARCHAR(100) NOT NULL,
  `emailCliente` VARCHAR(100) NOT NULL,
  `fone` VARCHAR(15) NOT NULL,
  `senha` CHAR(32) NOT NULL,
  `status` CHAR(1) NULL DEFAULT 'A',
  `Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`, `Cidade_idCidade`),
  CONSTRAINT `fk_Empresa_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `db_marESol`.`Cidade` (`idCidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nomeFuncionario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `fone` VARCHAR(16) NOT NULL,
  `CPF` CHAR(14) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `Cidade_idCidade` INT NOT NULL,
  `status` CHAR(1) NULL DEFAULT 'A',
  PRIMARY KEY (`idFuncionario`, `Cidade_idCidade`),
  CONSTRAINT `fk_Funcionario_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `db_marESol`.`Cidade` (`idCidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Movimento` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `observacao` VARCHAR(200) NULL,
  `aprovado` CHAR(1) NULL DEFAULT 'N',
  `entregue` CHAR(1) NULL DEFAULT 'N',
  `tipo` CHAR(1) NULL DEFAULT 'S',
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idVenda`, `Empresa_idEmpresa`),
  CONSTRAINT `fk_Movimento_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `db_marESol`.`Empresa` (`idEmpresa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_marESol`.`Movimento_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_marESol`.`Movimento_item` (
  `quantidade` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Movimento_idMovimento` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Movimento_idMovimento`),
  CONSTRAINT `fk_Produto_has_Movimento_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `db_marESol`.`Produto` (`idProduto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Venda_item_Venda1`
    FOREIGN KEY (`Movimento_idMovimento`)
    REFERENCES `db_marESol`.`Movimento` (`idVenda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
