php:
  image: php:7.4-apache
  container_name: my-php
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /home/developer/Documents/Programacao/teste-senai/www:/var/www/html
  links:
    - db

db:
  image: mysql:latest
  container_name: mysql-php
  ports:
    - "3306:3306"
  volumes:
    - var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root